# syntax=docker/dockerfile:1
   
FROM node:20-alpine

WORKDIR /app 

COPY ./package.json /app

RUN apk add --no-cache python3

RUN apk add --no-cache make gcc g++

RUN npm cache clean --force

RUN npm install

COPY . /app

CMD ["npm", "start"]

EXPOSE 3000